server:
  port: 8888
spring:
  application:
    name: lms
  datasource:
    url: jdbc:mysql://localhost:3306/lms
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
security:
  photon:
    username: photon
    password: photon@123
  personal:
    username: shekhar
    password: Shekhar@123
